[server]
headless = true
port = 3000
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 300
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#8A2BE2"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#161B22"
textColor = "#E6EDF3"
font = "sans serif"
